### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by mcg1969** [ContinuumIO/tranquilizer#28]
More details to come, but basically adding `flask-cors` support would be helpful for REST APIs that would be accessed via JavaScript.

**Comment by BenDavisson** [comment]
Thanks for making this issue for me @mcg1969 !

To add a little background..  I was working on building out tranquilizer Rest API's that can deliver resources to a web application.  I ran into some issues when trying to deploy the API's with Anaconda Enterprise.

I could deploy the tranquilizer API and send _post_ requests to the endpoints successfully by using the [requests](https://requests.readthedocs.io/en/master/) library from a python script.  However, when I tried to hit the end point using jQuery AJAX from a browser, I was hit with some CORS issues.  Specifically:   

`
Access to XMLHttpRequest at '<api-url>' from origin '<browser-url>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

After a bit of digging, I couldn't find any resources about tranquilizer that could help me handle CORS so I built a new API from scratch using only Flask and the [flask-cors](https://flask-cors.readthedocs.io/en/latest/) package.

The ```flask-cors``` package allows you to configure settings that can handle SOP/CORS effectively by enabling basically every origin possible.  They also provide methods to increase security by enabling only certain origins to access the requested resources.  

If tranquilizer could integrate the ```flask-cors``` package to handle CORS from the start... it may increase it's potential as a simple yet powerful Rest API deployment package.

**Comment by AlbertDeFusco** [comment]
Hey, there. Have you had a chance to test this?

**Comment by BenDavisson** [comment]
Sorry @AlbertDeFusco !  I should have tested this out months ago.  @jlstevens is working on using it and everything seems to be going as expected.

**Comment by AlbertDeFusco** [comment]
Great. I've included this in version 0.6.0 and it will be available on conda-forge today and defaults in the near future
