### ISSUE TITLE
issue with example on pypi.org

### ISSUE THREAD

**Issue by MichielBbal** [ContinuumIO/tranquilizer#35]
Really like this approach!

However, when I run the example as provided on pypi.org:
In [1]: import requests

In [2]: response = requests.get('http://localhost:8086/order', params={'cheese':'Red Leicester'})

In [3]: response.json()

Two remarks:
- you'll have to leave out 'order' from the url (http://localhost:8086) .
- response.json() triggers an error: 'JSONDecodeError: Expecting value: line 1 column 1 (char 0)'

**Comment by AlbertDeFusco** [comment]
Thank you! I've updated the README for release 0.6.0 and it is no correct here on github and on pypi
